export const DEFAULT_INTIAL_POSITION = {
  INITIAL_POSITION_X: 10,
  INITIAL_POSITION_Y: 10,
  EVERY_INDENT_WIDTH: 5,
  EVERY_TEXT_LINE_HEIGHT: 6,
};

export const A4_DEFAULT_CONFIG = {
  ...DEFAULT_INTIAL_POSITION,
  TEXT_LINE_MAX_WIDTH: 190,
  EVERY_PAGE_MAX_HEIGHT: 280,
};
